fga-eps-mds/2018.2-GamesBI

.travis.yml, requirements.txt
=> Add integration with coveralls.

_posts/docs/2018-08-27-doc_arquitetura.md
Foram adicionados nova visão geral da arquitetura e MER dos microserviços
#86 #85 #84 
Para que a importação de dados seja mais organizada e busque apenas dados necessários, foi pensado a criação de um novo microserviço que liste apenas jogos mais populares, que por sua vez também pode agregar novos atributos importantes para a análise de dados
=> Architeture doc

_posts/docs/2018-08-28-docs_visao.md
Co-authored-by: Lucas <lmlucasmachadom@gmail.com>
Signed-off-by: ingrdst <ingr.dcg@gmail.com>
#56
=> [DOC] #56 Updated Vision Document

GameColorBI/settings.py, docker-compose.yml, requirements.txt
Atualização da master após da sprint
=> [UPDATE] #66 Updated mongodb as database

_posts/docs/2018-08-27-doc_arquitetura.md
Adicionado diagrama de pacotes no documento de arquitetura
#101 
Guiar o time de desenvolvimento na padronização dos microserviços
=> [ADD] #101 Added packages diagram

_posts/docs/2018-08-27-doc_arquitetura.md
MER da twitch service atualizado, estava faltando game_id
#84
=> [DOC] #84 fix MER of the Twitch service

abertura/index.html, especificacao/visao.html, index.html, sprints/index.html, sprints/planning.html, sprints/review.html, sprints/sprint0planning.html, sprints/sprint0review.html, sprints/sprint1planning.html, sprints/sprint1review.html, sprints/sprint2planning.html, sprints/sprint2review.html, sprints/sprint3planning.html, sprints/teste.html
Adicionando a EAP, e completando a área "Sobre nós"
#114 2
=> Update gh pages

abertura/canvas.html
Atualizando documentações e criando canvas
#114
=> [DOC] #114 Create project model canvas

docs/docs/2018-08-27-doc_arquitetura.md, especificacao/arquitetura.html
Changed documentation architecture patterns and added React information content. Also updated MER schemes of microservices.
#137
=> Feature #137

docs/docs/2018-08-27-doc_arquitetura.md
MER do youtube e twitch atualizados
#137
=> [DOC] #137 Update twitch and youtube MER

docs/docs/2018-08-27-doc_arquitetura.md
Implementation of another field of crossdata UML
#137
=> [DOC] #137 Update crossdata with date field

CrossData/metabase/admin.py, CrossData/metabase/apps.py, CrossData/metabase/models.py, CrossData/metabase/serializers.py, CrossData/metabase/tests.py, CrossData/metabase/urls.py, CrossData/metabase/utils.py, CrossData/metabase/views.py, CrossData/settings.py, CrossData/urls.py, docker-compose.yml, makefiles/docker.mk, requirements.txt
Adicionei um end point para resgatar o uuid do iframe necessário
#173
=> [ADD] #173 Add post and get endpoints for iframes

docs/docs/2018-08-27-doc_arquitetura.md, especificacao/arquitetura.html
Criação do dicionario de dados
feature_#185
Essa issue foi motivada apos feedback da R1(Necessidade de descrição dos dados)
- [x ] New _feature_
=> Feature #185

docs/docs/2018-08-27-doc_arquitetura.md
Co-authored-by: Bruno Rodrigues Santos <bruesmanbruesman@hotmail.com>
Atualização da visão geral da arquitetura
Atualização das descrição dos microservices
Atualização do MER
#196 
Com o feedback da R1, implementamos alguns mudanças na arquitetura que podem melhorar o funcionamento do sistema
=> Atualização do Doc de Arquitetura

CrossData/settings.py, requirements.txt
Habilitei a configuração de CORS na aplicação
#205
A API recusava o acesso à partir de fontes externas, como por exemplo o front end. Após habilitar o CORS para todos os hosts, não há mais esse problema
Foi realizado uma requisição de dentro do front end para a api
=> [ADD] #205 Enable CORS to all hosts

makefiles/docker.mk, runserver.sh
Estava ocorrendo um erro aonde o serviço do Django não esperava o serviço do banco inicializar por completo. Com isso, o makefile foi alterado para que o django espere a inicialização do banco.
Inicialização dos serviços mais eficaz
=> Hotfix - Makefile corrigido para segmentar a inicialização dos serviços

CrossData/API/tests.py
Criação de novos testes.
Aumentar o nivel de cobertura de testes.
Foi testado apartir de testes unitarios.
=> #200 Add more test

CrossData/API/urls.py, CrossData/API/views.py, CrossData/importdata/serializers.py, CrossData/importdata/urls.py, CrossData/importdata/views.py, CrossData/urls.py
Criação de endpoint para retornar os nomes de jogos selecionados com base em um parâmetro 'name' no crossData
#204 
Irá permitir que tenham nomes de jogos disponíveis para serem apresentados a medida com que o usuário digite o nome de algum na barra de pesquisas
=> Feature #204

CrossData/API/views.py
Endpoint de nome de jogos atualizado para não usar sensitive case
Irá possibilitar que os jogos sejam buscados de uma forma mais abrangente
Foi testado manualmente, observando o parametro que foi passado e os dados retornados do endpoint
=> [HOTFIX] Update games endpoint used without sensitive case

CrossData/API/tests.py, CrossData/API/views.py, CrossData/importdata/models.py
Criação de novas models
Adaptação de endpoint POST para receber dados de imagens e paletas de cores
fga-eps-mds/2018.2-GamesBI#221
Será possivel enviar dados relacionados a imagens do jogo para o front end
O Importer service foi rodado juntamente com o CrossData, os dados foram importados pelo Importer e posteriormente enviados para o CrossData com sucesso. Os dados foram persistidos e verificados
nas models
=> Feature #221

docs/docs/2018-08-27-doc_arquitetura.md
Registro de models de languages e genres 
Registro de json enviado pelo importer
Será usado como parametro para atualizacao de dados no CrossData e Importer
=> [FIX] Update in models and json importer

CrossData/API/tests.py, CrossData/API/views.py, CrossData/importdata/models.py
Foram criados models Genre e Language;
Atualização do endpoint POST para receber novo formato de dados;
Foram atualizados os testes unitários.
#237 
Pegar mais de uma linguagem e gênero por jogo
Por meio de testes unitários.
=> Feature #237

CrossData/API/views.py
Tinha esquecido de adiconar os dados da model Game ao endpoint
#235
Estavam faltando dados no endpoint
Foi realizado uma requisição para o endpoint e confirmado que todos os dados estão sendo resgatados
=> [HOTFIX] Add game data to endpoint

CrossData/API/views.py
O endpoint /api/?name foi atualizado para retornar somente os dados mais recentes
Do jeito atual, esse endpoint quebrava caso tivesse mais de uma entrada do msm jogo no banco
Foi testado manualmente os endpoints afetados por essa mudança com mais de uma entrada no banco
=> [HOTFIX] Fix endpoint /api/?name not returning most recent data

CrossData/API/views.py, requirements.txt
Apenas mudei o formato da release_date novamente, visto que ele tava dando problema ao pegar algum jogo no qual a data não é convencional, por exemplo: 'Jul 2018'
=> [HOTFIX] Fix datetime format with new package

CrossData/API/views.py
Corrigindo falha no nome dos eixos dos gráficos de um jogo
Correção de erro na importação de gráficos lineares
=> [HOTFIX] Update field name

CrossData/API/tests_get_data.py, CrossData/API/views.py
Mudei o nome de uns campos e variaveis
Os nomes estavam errados e por causa disso o front não resgatava os dados corretamente
Assim que foi realizado o deploy, foi visto que os gráficos estavam normais novamente
=> [HOTFIX] Change axys to axis on some field names

CrossData/API/models.py, CrossData/API/tests.py, CrossData/API/views.py
Refatoração do codigo
refatorar o código para facilitar o entendimento e alguma futura ou atual manutenção, seguindo os padrões do pep8
#256 
Para facilitar o entendimento e a manutenibilidade do código.
Utilizando o linter pep8 para verificar a qualidade do código e apos as mudanças foi verificado.
=> Feature #256
